/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgramsRouteImport } from './routes/_authenticated/programs'
import { Route as AuthenticatedAdministratorsRouteImport } from './routes/_authenticated/administrators'
import { Route as AuthenticatedProgramsIndexRouteImport } from './routes/_authenticated/programs.index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings.system'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedMonitoringOverviewRouteImport } from './routes/_authenticated/monitoring.overview'
import { Route as AuthenticatedMonitoringAuditRouteImport } from './routes/_authenticated/monitoring.audit'
import { Route as ApiPublicV2SplatRouteImport } from './routes/api/public/v2/$'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as AuthenticatedProgramsProgramIdVersionsRouteImport } from './routes/_authenticated/programs.$programId.versions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgramsRoute = AuthenticatedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministratorsRoute =
  AuthenticatedAdministratorsRouteImport.update({
    id: '/administrators',
    path: '/administrators',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramsIndexRoute =
  AuthenticatedProgramsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProgramsRoute,
  } as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringOverviewRoute =
  AuthenticatedMonitoringOverviewRouteImport.update({
    id: '/monitoring/overview',
    path: '/monitoring/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringAuditRoute =
  AuthenticatedMonitoringAuditRouteImport.update({
    id: '/monitoring/audit',
    path: '/monitoring/audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicV2SplatRoute = ApiPublicV2SplatRouteImport.update({
  id: '/api/public/v2/$',
  path: '/api/public/v2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgramsProgramIdVersionsRoute =
  AuthenticatedProgramsProgramIdVersionsRouteImport.update({
    id: '/$programId/versions',
    path: '/$programId/versions',
    getParentRoute: () => AuthenticatedProgramsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/administrators': typeof AuthenticatedAdministratorsRoute
  '/programs': typeof AuthenticatedProgramsRouteWithChildren
  '/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/monitoring/overview': typeof AuthenticatedMonitoringOverviewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/programs/': typeof AuthenticatedProgramsIndexRoute
  '/programs/$programId/versions': typeof AuthenticatedProgramsProgramIdVersionsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/v2/$': typeof ApiPublicV2SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/administrators': typeof AuthenticatedAdministratorsRoute
  '/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/monitoring/overview': typeof AuthenticatedMonitoringOverviewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/programs': typeof AuthenticatedProgramsIndexRoute
  '/programs/$programId/versions': typeof AuthenticatedProgramsProgramIdVersionsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/v2/$': typeof ApiPublicV2SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_authenticated/administrators': typeof AuthenticatedAdministratorsRoute
  '/_authenticated/programs': typeof AuthenticatedProgramsRouteWithChildren
  '/_authenticated/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/_authenticated/monitoring/overview': typeof AuthenticatedMonitoringOverviewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/programs/': typeof AuthenticatedProgramsIndexRoute
  '/_authenticated/programs/$programId/versions': typeof AuthenticatedProgramsProgramIdVersionsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/v2/$': typeof ApiPublicV2SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/administrators'
    | '/programs'
    | '/monitoring/audit'
    | '/monitoring/overview'
    | '/settings/account'
    | '/settings/profile'
    | '/settings/system'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/programs/'
    | '/programs/$programId/versions'
    | '/api/public/v1/$'
    | '/api/public/v2/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/administrators'
    | '/monitoring/audit'
    | '/monitoring/overview'
    | '/settings/account'
    | '/settings/profile'
    | '/settings/system'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/programs'
    | '/programs/$programId/versions'
    | '/api/public/v1/$'
    | '/api/public/v2/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/_authenticated/administrators'
    | '/_authenticated/programs'
    | '/_authenticated/monitoring/audit'
    | '/_authenticated/monitoring/overview'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/system'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/_authenticated/programs/'
    | '/_authenticated/programs/$programId/versions'
    | '/api/public/v1/$'
    | '/api/public/v2/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
  ApiPublicV2SplatRoute: typeof ApiPublicV2SplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administrators': {
      id: '/_authenticated/administrators'
      path: '/administrators'
      fullPath: '/administrators'
      preLoaderRoute: typeof AuthenticatedAdministratorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programs/': {
      id: '/_authenticated/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof AuthenticatedProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedProgramsRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring/overview': {
      id: '/_authenticated/monitoring/overview'
      path: '/monitoring/overview'
      fullPath: '/monitoring/overview'
      preLoaderRoute: typeof AuthenticatedMonitoringOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring/audit': {
      id: '/_authenticated/monitoring/audit'
      path: '/monitoring/audit'
      fullPath: '/monitoring/audit'
      preLoaderRoute: typeof AuthenticatedMonitoringAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v2/$': {
      id: '/api/public/v2/$'
      path: '/api/public/v2/$'
      fullPath: '/api/public/v2/$'
      preLoaderRoute: typeof ApiPublicV2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/programs/$programId/versions': {
      id: '/_authenticated/programs/$programId/versions'
      path: '/$programId/versions'
      fullPath: '/programs/$programId/versions'
      preLoaderRoute: typeof AuthenticatedProgramsProgramIdVersionsRouteImport
      parentRoute: typeof AuthenticatedProgramsRoute
    }
  }
}

interface AuthenticatedProgramsRouteChildren {
  AuthenticatedProgramsIndexRoute: typeof AuthenticatedProgramsIndexRoute
  AuthenticatedProgramsProgramIdVersionsRoute: typeof AuthenticatedProgramsProgramIdVersionsRoute
}

const AuthenticatedProgramsRouteChildren: AuthenticatedProgramsRouteChildren = {
  AuthenticatedProgramsIndexRoute: AuthenticatedProgramsIndexRoute,
  AuthenticatedProgramsProgramIdVersionsRoute:
    AuthenticatedProgramsProgramIdVersionsRoute,
}

const AuthenticatedProgramsRouteWithChildren =
  AuthenticatedProgramsRoute._addFileChildren(
    AuthenticatedProgramsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdministratorsRoute: typeof AuthenticatedAdministratorsRoute
  AuthenticatedProgramsRoute: typeof AuthenticatedProgramsRouteWithChildren
  AuthenticatedMonitoringAuditRoute: typeof AuthenticatedMonitoringAuditRoute
  AuthenticatedMonitoringOverviewRoute: typeof AuthenticatedMonitoringOverviewRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministratorsRoute: AuthenticatedAdministratorsRoute,
  AuthenticatedProgramsRoute: AuthenticatedProgramsRouteWithChildren,
  AuthenticatedMonitoringAuditRoute: AuthenticatedMonitoringAuditRoute,
  AuthenticatedMonitoringOverviewRoute: AuthenticatedMonitoringOverviewRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
  ApiPublicV2SplatRoute: ApiPublicV2SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
