name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: crpi-lymsz4btgausoaex.cn-shanghai.personal.cr.aliyuncs.com
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: crpi-lymsz4btgausoaex.cn-shanghai.personal.cr.aliyuncs.com/updaterserver/admin:latest,crpi-lymsz4btgausoaex.cn-shanghai.personal.cr.aliyuncs.com/updaterserver/admin:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment updater-admin